## **Question-1**

### How to find the missing number in an integer array of 1 to 100?

In [1]:
def missingNumber(array,n):
    return sumOfN(n)-sum(array)

def sumOfN(n):
    if(n==0):
        return 0
    else:
        return n+sumOfN(n-1)

In [2]:
n=100
array=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,
        29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,
        54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,73,74,75,76,77,78,
        79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100]
missingNumber(array,n)

72

##### Iterate through the list and compute the sum of all numbers. Now, sum of natural numbers from 1 to N, can be expressed as Nx(N+1)/2. In this case we have N=100. For sum we have created a recursive function *sumOfN*.

##### Subtract the sum of the array from sum of N terms, where N=100.

##### That is the missing number.

## **Question-2**

### Write a program to find all pair of integers whose sum is equal to a given number.

In [3]:
def pairsum(array,n):
    for i in range(len(array)):
#         for j in range(0,len(array)): # For range(0,len(array)) it will also give the pairs of similar numbers like (1,15) and (15,1) 
#         for j in range(i,len(array)): # For range(i,len(array)) it will also give pair of (8,8) that is of same numbers 
        for j in range(i+1,len(array)):
            if array[i]+array[j]==n:
                print("Pairs of integers whose sum is equal to n is : " + 
                      "(" + str(array[i]) + "," + str(array[j]) + ")")

In [4]:
import numpy as np
array=np.linspace(1,20,20)
array
arr=array.astype('int32')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [5]:
array=arr
n=16
pairsum(array,n)

Pairs of integers whose sum is equal to n is : (1,15)
Pairs of integers whose sum is equal to n is : (2,14)
Pairs of integers whose sum is equal to n is : (3,13)
Pairs of integers whose sum is equal to n is : (4,12)
Pairs of integers whose sum is equal to n is : (5,11)
Pairs of integers whose sum is equal to n is : (6,10)
Pairs of integers whose sum is equal to n is : (7,9)


## **Question-3**

### How to check is an array contains a number in Python?

In [6]:
import numpy as np
array=np.linspace(1,20,20)
arr=array.astype('int32')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [7]:
def findNumber(array,number):
    for i in range(0,len(array)):
        if array[i]==number:
            return ("Number found at: " + str(i))
    return ("Number doesn't exist in this array")

In [8]:
array=arr
number=12
findNumber(array,number)

'Number found at: 11'

## **Question-4**

### How to find maximum product of two integers in the array where all elements are positive?

In [9]:
def findMaxProduct(array):
    maxProduct=0
    for i in range(0,len(array)):
        for j in range(i+1,len(array)):
            if (array[i]*array[j]>maxProduct):
                maxProduct=array[i]*array[j]
                pairs=str(array[i]) + "," + str(array[j]) + "," +" Product is " + str(array[i]*array[j])
    print(pairs)

In [10]:
import numpy as np
array=100*np.random.rand(21)
arr=array.astype('int32')
arr

array([31, 22, 30, 93, 99, 52, 73, 55, 72,  1, 59, 46, 91, 28, 48, 92, 48,
       90, 13, 88, 46])

In [11]:
array=arr
findMaxProduct(array)

93,99, Product is 9207


## **Question-5**

### Is Unique: Implement an algorithm to determine if a list has all unique characters, using python list.

In [12]:
myList=[1,20,30,44,5,56,57,8,19,10,31,12,13,14,15,35,16,27,58,19,21]
def isUnique(List):
    for i in range(0,len(List)):
        for j in range(i+1,len(List)):
            if List[i]==List[j]:
                print("The Non Unique Number is : " + str(List[i])) 

In [13]:
isUnique(myList)

The Non Unique Number is : 19


## **Question-6**

### Permutation

In [14]:
def permutation(list1,list2):
    list2.reverse()
    if list1==list2:
        return True
    else:
        return False

In [15]:
list1=[1,2,3]
list2=[3,2,1]
permutation(list1,list2)

True

## **Question-7**

### Rotate Matrix

In [16]:
import numpy as np
myarray=np.array([[1,2,3],[4,5,6],[7,8,9]])
myarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
def rotMatrix(matrix):
    n=len(matrix)
    for layer in range(n//2):
        first=layer
        last=n-layer-1
        for i in range(first,last):
            # save top
            top = matrix[layer][i]

            # left -> top
            matrix[layer][i] = matrix[-i - 1][layer]

            # bottom -> left
            matrix[-i - 1][layer] = matrix[-layer - 1][-i - 1]

            # right -> bottom
            matrix[-layer - 1][-i - 1] = matrix[i][- layer - 1]

            # top -> right
            matrix[i][- layer - 1] = top
    return matrix
    

In [22]:
matrix=myarray
rotMatrix(matrix)

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])